FactoryBot.define do
  factory :invoice do
    association :customer
    association :created_by, factory: :user

    invoice_date  { Time.zone.today }
    status        { "Dr" }
    total_amount  { 0 }
    invoice_number { nil } # generated by callback

    trait :paid do
      status { "Pd" }
    end

    trait :cancelled do
      status { "Cc" }
    end
  end
end
