inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/AbcSize:
  Max: 25

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Rails/FilePath:
  Enabled: false
